@startuml
'https://plantuml.com/class-diagram

class MainActivity {
    #onCreate(savedInstanceState: Bundle)
}

class ProfileFragment {
    -TextView firstName
    -TextView lastName
    -TextView contact
    -ImageView profPic
    -UserController userController
    -DatabaseController databaseController
    -TabLayout tabLayout
    -FrameLayout frameLayout
    #onCreate(savedInstanceState: Bundle)
}

class UserController {
    -User user
    -String defaultUUID
    -String prefName
    +User getUser()
    +setUser(user: User)
    +String getUserID(context: Context)
    +saveUUID(context: Context, id: String)
    +selectImage(activity: Activity)
    +selectImage(fragment: Fragment)
    +editProfile(firstName: String, lastName: String,
    contact: String, pictureUri: Uri)
    +checkIn(event: Event)
}

class DatabaseController {
    -FirebaseFirestore db
    -FirebaseStorage storage
    +putUserToFirestore(user: User)
    +updateWithUserFromFirestore(id: String, userController: UserController)
    +getUserFromFirestore(id: String, callback: UserCallback)
    +uploadProfilePicture(picture: Uri, user: User)
    +updateWithProfPictureFromWeb(user: User)
    +getUserProfilePicture(userID: String, callback: ImageUriCallback)
    +putEventPosterToFirestore(String: eventID, Uri imageUri)
    +putEventCheckInQRCodeToFirestore(String: eventID, Uri imageUri)
    +putEventDesscriptionQRCodeToFirestore(String: eventID, Uri imageUri)
    +getEventPoster(String eventID, callback: EventImageUriCallbacks)
    +getEventCheckInQRCode(String eventID, callback: EventImageUriCallbacks)
    +getEventDescriptionQRCode(String eventID, callback: EventImageUriCallbacks)
    +pushEventToFirestore(event: Event)
    +getEventFromFirestore(eventID: String, callback: GetEventCallback)
    +getAllEventsFromFirestore(callback: GetAllEventsCallback)
}

class Event {
    -String id
    -String name
    -int capacity
    -Collection<String> signedUpUsers
    -Collection<String> checkedInUsers
    -Uri eventPoster
    -Uri checkInQrCodeUri
    -Uri descriptionQRCodeUri
    -Object location
    -Date date
    -String creatorUUID
    -String description
    +String getCreatorUUID()
    +setCreator(creatorUUID: string)
    +String getUuid()
    +setUuid(id: String)
    +String getName()
    +setName(name: String)
    +setLocation(String location)
    +int getCapacity()
    +setCapacity(capacity: int)
    +boolean isCapped()
    +boolean isFull()
    +addCheckedInUser(uuid: String)
    +Collection<String> getCheckedInUsersUUIDs()
    +boolean isUserCheckedIn(user: User)
    +addSignedUpUser(uuid: String)
    +Collection<String> getSignedUpUsersUUIDs()
    +boolean isUserSignedUp(user: User)
    +setCheckInQRCodeUri(Uri checkInQrCodeUri)
    +Uri getCheckInQRCodeUri()
    +setDescriptionQRCodeUri(Uri getDescriptionQRCodeUri)
    +Uri getDescriptionQRCodeUri()
}

class EventController{
  -Event event
  +checkInUser(uuid: String)
  +signUpUser(uuid: String)
}


class User {
    -String profilePicPath
    -String id
    -String firstName
    -String lastName
    -String contact
    -ArrayList<String> attendingEvents
    -ArrayList<String> hostingEvents
    -Uri picture
    -String imgUrl
    +String getId()
    +setId(id: String)
    +String getFirstName()
    +setFirstName(firstName: String)
    +String getLastName()
    +setLastName(lastName: String)
    +ArrayList<String> getAttendingEvents()
    +ArrayList<String> getHostingEvents()
    +String getContact()
    +setContact(contact: String)
    +Uri getPicture()
    +setPicture(picture: Uri)
    +String getImgUrl()
    +setImgUrl(imgUrl: String)
}

class CheckInFragment {
    -DatabaseController databaseController
    -ActivityResultLauncher<ScanOptions> scanLauncher
    -processResult(ScanIntentResult: result)
}


CheckInFragment <|.. ScanButtonListener : implements
CheckInFragment <|.. GetEventCallback : implements

class EditProfileFragment {
    -OnProfileUpdateListener profileUpdateListener
    -EditText firstName
    -EditText lastName
    -EditText contact
    -ImageView profPic
    -UserController userController
    +setOnProfileUpdateListener(listener: OnProfileUpdateListener)
}


class Fragment
class DialogFragment

interface OnProfileUpdateListener {
    +onProfileUpdate(newFirstName: String, newLastName: String, newContact: String, newPicture: Uri)
}

class EventArrayAdapter {
    -ArrayList<Event> events
    -Context context
    +getView(position: int, convertView: View, parent: ViewGroup
}

interface GetAllEventsCallback {
    +onGetAllEventsCallback(event: Event)
}

interface ImageUriCallback{
  +OnImageUriCallback(imageUri: Uri)
  +OnError(e: Exception)
}

interface UserCallback{
  +OnCallback(imageUri: Uri)
  +OnError(e: Exception)
}

class HomeFragment {
    -DatabaseController dbController
    -ArrayList<Event> events
    -ListView eventsList
    -EventArrayAdapter eventsArrayAdapter
    -EventDetailsFragment frag
}

class EventDetailsFragment {
    -TextView eventDescription
    -TextView announcement
    -ImageView eventPoster
    -Button backButton
    +newInstance(Event event)
}

class AttendeeListActivity {
    -eventTitle: TextView
    -checkedInCountText: TextView
    -signedUpCountText: TextView
    -checkedInListView: ListView
    -signedUpListView: ListView
    -switchToMapButton: Button
    -signedUpUserAdapter: UserArrayAdapter
    -checkedInUserAdapter: UserArrayAdapter
    -dbController: DatabaseController
    -event: Event
    -signedUpUsers: ArrayList<User>
    -checkedInUsers: ArrayList<User>
}

HomeFragment "1" o-- "0...*" EventDetailsFragment
EventDetailsFragment "1" *-- "1" Event

Fragment <|-- ProfileFragment
Fragment <|-- CheckInFragment
Fragment <|-- EventCreationFragment
Fragment <|-- EventDetailsFragment
Fragment <|-- HomeFragment

ArrayAdapter <|-- EventArrayAdapter
ArrayAdapter <|-- UserArrayAdapter

DialogFragment <|-- EditProfileFragment
DialogFragment <|-- QRCodeFragment

AlertDialog <|-- CheckInConfirmationDialog


AppCompatActivity <|-- MainActivity : extends
AppCompatActivity <|-- AttendeeListActivity : extends

ProfileFragment <|.. OnProfileUpdateListener : implements
ProfileFragment "0...1" o-- "1" DatabaseController
ProfileFragment "0...1" o-- "1" UserController
ProfileFragment "1" -- "1" User

MainActivity "0...1" o-- "1" DatabaseController
MainActivity "0...1" o-- "1" UserController

EditProfileFragment "0...1" o-- "1" DatabaseController
EditProfileFragment "0...1" o-- "1" UserController
EditProfileFragment "0...1" o-- "1" User

AttendeeListActivity "0...1" o-- "0..*" User

HomeFragment "0...1" o-- "1" DatabaseController
HomeFragment "0..1" *-- "1" EventArrayAdapter
GetAllEventsCallback <|.. HomeFragment
GetCheckedInUsersCallback <|.. AttendeeListActivity
GetSignedUpUsersCallback <|.. AttendeeListActivity

UserController "0...1" o-- "1" User : has
EventController "0..1" o-- "1" Event
DatabaseController "0..." -- "0..." User
DatabaseController "0..." -- "0..." UserController

CheckInFragment "0...1" o-- "1" DatabaseController : has

EventCreationFragment "0...1" o-- "1" DatabaseController
EventCreationFragment "0...1" o-- "1" UserController
EventCreationFragment "0...1" o-- "1" QRCodeFragment

EditProfileFragment o-- UserController
ProfileFragment "1" *-- "0...1" EditProfileFragment
Event "0..." -l- "0..." User

skinparam nodesep 25
skinparam ranksep 25
skinparam linetype ortho
@enduml
